spring:
  datasource:
    url: jdbc:mysql://192.168.1.142:3306/professordb?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&dialect=MySQL57Dialect
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.qq.com
    username: 1101029203@qq.com
    password: yezssrffpkucjdfj
jwt:
  secret: panle
  expiration: 604800
  header: Authorization
  tokenHead: Bearer
logging:
  com.security.demo: DEBUG
server:
  port: 8099

