spring:
  datasource:
#    url: jdbc:mysql://192.168.1.142:3306/professordb_new?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&dialect=MySQL57Dialect
#    username: root
#    password: root
    url: jdbc:mysql://rm-hp384ht74xir31xdazo.mysql.huhehaote.rds.aliyuncs.com:3306/profession_volunteer?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&dialect=MySQL57Dialect
    username: profession
    password: 6WPHeceb1gPl5iwL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#  mail:
#    host: smtp.qq.com
#    username: 1101029203@qq.com
#    password: yezssrffpkucjdfj
jwt:
  secret: panle
  expiration: 604800
  header: Authorization
  tokenHead: Bearer
logging:
  com.security.demo: DEBUG
#server:
#  port: 8207
jackson:
  serialization:
    fail-on-empty-beans: false
server:
  port: 8099
