spring:
  datasource:
    url: jdbc:mysql://192.168.1.142:3306/professordb?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.163.com
    username: m15570719300@163.com
    password: pl123456
    web:
      pageable:
        max-page-size: 20
jwt:
  secret: panle
  expiration: 604800
  header: Authorization
  tokenHead: Bearer
logging:
  com.security.demo: DEBUG
server:
  port: 8099

